
logging:
  pattern:
    level: '%5p %mdc'

pulsar:
  service-url: pulsar://localhost:6650

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health

  endpoint:
    health:
      enabled: true
      show-details: always
      show-components: always
      probes:
        enabled: true
        add-additional-paths: true
      group:
        liveness:
          include: livenessState
          additional-path: server:/livez
        readiness:
          include: readinessState
          additional-path: server:/health
  health:
    defaults:
      enabled: false
    livenessState:
      enabled: true
    readinessState:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: localhost-ssl

pulsar:
  service-url: pulsar+ssl://localhost:6651


---
spring:
  config:
    activate:
      on-profile: docker-nossl

pulsar:
  service-url: pulsar://pulsar:6650


---
spring:
  config:
    activate:
      on-profile: docker-ssl

pulsar:
  service-url: pulsar://pulsar:6651
