
logging:
  pattern:
    level: '%5p %mdc'

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health

  endpoint:
    health:
      enabled: true
      show-details: always
      show-components: always
      probes:
        enabled: true
        add-additional-paths: true
      group:
        liveness:
          include: livenessState
          additional-path: server:/livez
        readiness:
          include: readinessState
          additional-path: server:/health
  health:
    # by default disable all health indicators and only enable the ones in our readiness/liveness groups.
    defaults:
      enabled: false
    livenessState:
      enabled: true
    readinessState:
      enabled: true
